name: Run Files Sequentially on Windows

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: "0 */3 * * *"

jobs:
  run-files:
    runs-on: windows-latest # Use a Windows runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Specify a stable Python version

      - name: Install Python libraries
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests urllib3 regex

      - name: Check if BG token is valid
        run: |
          echo "Running script for BG tv token check"
          python test_available_token.py

      - name: Download Google Chrome installer 
        run: |
           $installerPath = "$env:TEMP\chrome_installer.exe" 
           Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile $installerPath 
      
      - name: Install Google Chrome
        run: |
           Start-Process -FilePath "$env:TEMP\chrome_installer.exe" -ArgumentList "/silent /install" -Wait 

      - name: install ChromeDriver
        run: |
          echo "Attempting to download ChromeDriver from: $driver_url"
          $driver_url = "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.205/win64/chromedriver-win64.zip"
          Invoke-WebRequest -Uri $driver_url -OutFile chromedriver-win64.zip
          Expand-Archive -Path chromedriver-win64.zip -DestinationPath C:\chromedriver
          [System.Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';C:\chromedriver', [System.EnvironmentVariableTarget]::Machine)

      - name: Extract channels from https://iptv-bg.com
        run: |
          echo "Running first file..."
          python channels_from_iptvbg.py

      - name: Wait for 3 seconds
        run: |
          Start-Sleep -Seconds 3

      - name: Renew global playlist
        run: |
          echo "Running second file..."
          python make_playlist.py

      - name: Configure Git
        run: |
          git config --global user.name "mmmw"
          git config --global user.email "mmmw@abv.bg"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Automated update: Ran scripts and updated files" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
